### ISSUE TITLE
clicking links to `dms-view` should open new windows

### ISSUE THREAD

**Issue by jbloom** [dms-view/docs#1]
In the docs, at least the links for clicking on specific views of `dms-view` with the flu data sets might be better if they opened a new window rather than change the current window to the `dms-view` example? This is especially true for the ones where it suggests clicking on different views: this would be easier if each click opened a new window so they could then be compared.

**Comment by skhilton** [comment]
At first I thought this was going to be impossible but you can replace the markdown syntax `[text](link)` with html `<a href="link" target="_blank">text</a>`. 

closed by commit b4280bd6
