### ISSUE TITLE
fixing metrics in case studies

### ISSUE THREAD

**Issue by jbloom** [dms-view/docs#3]
The case studies show the wrong metric for the mutation-level in all cases. 

For influenza, they should show positive mutation-level differential selection in the logoplots to match the papers, not both positive and negative.

For HIV, the values on the y-axis do not match from the figure images and the `dms-view`. I suspect it might be because one is fracsurvive and the other is diffsel?

In any case, since the case studies claim to be showing the correspondence between the two datasets, it would be good for them to show the same data in both.

**Comment by skhilton** [comment]
Fixed by commits acbe7b98 and dfeff971
